#!/bin/sh

set -x

cd /git-repo/build-context

cat *

echo $PODMAN_USER $PODMAN_PASSWORD $PODMAN_REGISTRY

podman login -u $PODMAN_USER -p $PODMAN_PASSWORD $PODMAN_REGISTRY
podman build -t $IMAGE_TAG .
podman push $PODMAN_REGISTRY/$PODMAN_USER/$IMAGE_TAG
