apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  description: |
    This pipeline clones a git repo, builds an image, and pushes it to a registry
  params:
    - name: repo-url
      type: string
    - name: image-tag
      type: string
    - name: podman-user
      type: string
    - name: podman-registry
      type: string
  workspaces:
    - name: podman-password
  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
      workspaces:
        - name: podman-password
          workspace: podman-password
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: image-tag
          value: $(params.image-tag)
        - name: podman-user
          value: $(params.podman-user)
        - name: podman-registry
          value: $(params.podman-registry)
