name: build-push
run-name: Building new container image
on:
  push:
    paths:
      - 'build-context/**'
jobs:
  build-and-push:
    runs-on: quay.io/vraiti/image-builder:latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: build-and-push
        run: build-and-push
        env:
          PODMAN_USER: "vraiti"
          PODMAN_PASSWORD: ${{ secrets.podman_password }}
          PODMAN_REGISTRY: "quay.io"
          IMAGE_TAG: "demo"
