name: build-push
run-name: Building new container image
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: quay.io/vraiti/image-builder:latest 
      env:
        PODMAN_USER: "vraiti"
        PODMAN_PASSWORD: ${{ secrets.podman_password }}
        PODMAN_REGISTRY: "quay.io"
        IMAGE_TAG: "demo"
        GITHUB_WORKSPACE: "/home"
      volumes:
        - /home
    steps:
      - name: checkout
        run: git clone https://github.com/${{ github.action_repository }}.git /home
      
      - name: build-and-push
        run: build-and-push
