name: build-push
run-name: Building new container image
on: [push]
env:
  USER: vraiti
  PASSWORD: ${{ secrets.PODMAN_PASSWORD }}
  REGISTRY: quay.io
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:  
      - name: checkout
        uses: actions/checkout@v4

      - name: login
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.USER }}
          password: ${{ env.PASSWORD }}
          registry: ${{ env.REGISTRY }}
      
      - name: build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: "demo"
          tags: "latest"
          containerfiles: |
            ./build-context/Containerfile

      - name: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.REGISTRY }}/${{ env.USER }}
