name: build-push
run-name: Building new container image
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:  
      - name: checkout
        uses: actions/checkout@v4

      - name: buildah
        uses: redhat-actions/buildah-build@v2
        with:
          image: "demo"
          tags: "latest"
          containerfiles: |
            ./build-context/Containerfile
